name:  bBasic
version:  1.0
main:  me.brawl.Main.Main
commands:
   kick:
     permission: brawl.kick
   ban:
     permission: brawl.ban
   msg:
     permission: brawl.msg
   vanish:
     permission: brawl.vanish
   whois:
     permission: brawl.whois
   fly:
     permission: brawl.fly
   admin:
     permission: brawl.admin
   whois:
     permission: brawl.whois
   fly:
     permission: brawl.fly
   day:
     permission: brawl.time
   night:
     permission: brawl.time
   list:
     description: List currently online players
   suicide:
     description: Kills you!
   tp:
     permission: brawl.tp
   gm:
     permission: brawl.gamemode